mysite/accounts/urls.py
from rest_framework import routers
from django.contrib import admin
from .views import UserProfile,NewUser,NewClinicUser,Userprofiler,ClinicProfiler
from . import views
from django.urls import include, path
app_name ="accounts"

router = routers.DefaultRouter()
router.register(r'users', views.UserProfile, basename='users')
router.register(r'users/<int:id>', views.UserProfile, basename='users_update')

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('newuser/',NewUser.as_view(), name='newuser'),
    path('newclinicuser/',NewClinicUser.as_view(), name='newclinicuser'),
    path('userprofile/',Userprofiler.as_view(), name='userprofile'),
    path('clinicprofile/',ClinicProfiler.as_view(), name='clinicprofile'),
]

mysite/clinics/urls.py
from django.urls import path,include
from clinics.views import ClinicsView,NewClinic,ClinicDetails

app_name ="clinics"

urlpatterns = [

    path('clinics/',ClinicsView.as_view(), name='clinics'),
    path('newclinics/',NewClinic.as_view(), name='newclinics'),
    path('details/<int:id>/',ClinicDetails.as_view(), name='clinic_details'),



]

mysite/home/urls.py
from django.urls import path,include
from home.views import IndexView

app_name ="home"

urlpatterns = [

    path('',IndexView.as_view(), name='index'),
    path('accounts/', include('django.contrib.auth.urls')),



]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', 'accounts')),
    path('clinics/', include('clinics.urls', 'clinics')),
    path('booking/', include('booking.urls', 'booking')),
    path('', include('home.urls', 'home')),
    path('auth/', include('rest_framework.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/forms.py
from django import forms

class InsertClinic(forms.Form):
    name = forms.CharField(max_length=30)
    address = forms.CharField(max_length=30)
    phone = forms.CharField(max_length=30 )
    image = forms.ImageField()

mysite/templates/base.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="fa" />
        <meta name="keywords" content="">
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, shrink-to-fit=no" />
        <link rel="apple-touch-icon" sizes="57x57" href="{% static 'assets/favicon/apple-icon-57x57.png' %}">
        <link rel="apple-touch-icon" sizes="60x60" href="{% static 'assets/favicon/apple-icon-60x60.png' %}">
        <link rel="apple-touch-icon" sizes="72x72" href="{% static 'assets/favicon/apple-icon-72x72.png' %}">
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/favicon/apple-icon-76x76.png' %}">
        <link rel="apple-touch-icon" sizes="114x114" href="{% static 'assets/favicon/apple-icon-114x114.png' %}">
        <link rel="apple-touch-icon" sizes="120x120" href="{% static 'assets/favicon/apple-icon-120x120.png' %}">
        <link rel="apple-touch-icon" sizes="144x144" href="{% static 'assets/favicon/apple-icon-144x144.png' %}">
        <link rel="apple-touch-icon" sizes="152x152" href="{% static 'assets/favicon/apple-icon-152x152.png' %}">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/favicon/apple-icon-180x180.png' %}">
        <link rel="icon" type="image/png" sizes="192x192"  href="{% static '/android-icon-192x192.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/favicon/favicon-96x96.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static '{% static 'assets/favicon/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png' %}">
        <meta name="theme-color" content="#ffffff">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'assets/fonts/fonts.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/cbx.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
        <link href="{% static 'assets/css/flickity.css' %}"  rel="stylesheet" type="text/css" />
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="{% static 'assets/js/main.js' %}"></script>

    </head>
    <body>
        <div id="top"></div>
        <div class="modal-login">
            <div class="border-glass">
                <div id="login-signup">
                    <a href="javascript:void(0)" id="close-modal"><i class="fa fa-close"></i></a>

                        <ul class="nav nav-tabs">

                            <li style="display:none"><a id="dontRemember" data-toggle="tab" href="#dontRem"></a></li>
                        </ul>

                        <div class="tab-content">
                            <div id="login" class="tab-pane fade show active">
                                <form id="loginform"  action="">

                                    <input required="required" class="default-input login-input" type="password" name="txtPass">
                                    <input class="inp-cbx" id="cbxRemember" type="checkbox" style="display: none;"/>
                                    <label class="cbx" for="cbxRemember">
                                        <span>
                                            <svg width="12px" height="10px" viewbox="0 0 12 10">
                                                <polyline points="1.5 6 4.5 9 10.5 1"></polyline>
                                            </svg>
                                        </span>

                                    </label>


                                </form>
                            </div>
                            <div id="signup" class="tab-pane fade">
                                <form id="signupform"  action="">

                                </form>
                            </div>
                            <div id="dontRem" class="tab-pane fade">
                                <form id="dontRemform"  action="">

                                    <input required="required" class="default-input login-input" type="email" name="txtNewUser">

                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>


        <nav id="mynav" class="rtl">

          <br>
            <div class="navbar-brand">

            </div>
            <span class="navbar-toggle"><span></span></span>
&nbsp;
            <div class="">
              <br>
              {% if user.is_authenticated %}
  &nbsp;&nbsp; Hi {{ user.username }}! &nbsp;&nbsp;

  <p><a href="{% url 'home:logout' %}">Log Out</a></p> &nbsp;&nbsp;
  <p><a href="{% url 'home:index' %}">Home</a></p>&nbsp;&nbsp;
  <p><a href="{% url 'accounts:userprofile' %}">User Profile</a></p>&nbsp;&nbsp;
  <p><a href="{% url 'accounts:clinicprofile' %}">Clinic Profile</a></p>&nbsp;&nbsp;

{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'home:login' %}">Log In</a>
  <i  class=""><a href="{% url 'accounts:newuser' %}">User Signup</a></i>&nbsp;&nbsp;
   <i  class=""><a href="{% url 'accounts:newclinicuser' %}">Clinic Signup</a></i>&nbsp;&nbsp;
{% endif %}



            </div>


            <ul>


                    <ul>


                            <ul>

                            </ul>
                        </li>

                            <ul>



                            </ul>
                        </li>


                            <ul>


                            </ul>
                        </li>


                            <ul>

                            </ul>
                        </li>


                            <ul>

                            </ul>
                        </li>


                            <ul>


                            </ul>
                        </li>


                            <ul>

                            </ul>
                        </li>


                            <ul>


                            </ul>
                        </li>


                            <ul>


                            </ul>
                        </li>

                    </ul>
                </li>



                    <ul>

                    </ul>
                </li>


            </ul>

        </nav>

                {% block content %}


                {% endblock %}



                        <section id="footer">
                            <div class="row">
                                <div class="col-md-3 col-sm-12 p-0">

                                </div>
                                <div class="col-md-3 col-sm-12 p-0">

                                </div>
                                <div class="col-md-3 col-sm-12 p-0">

                                </div>
                                <div class="col-md-3 col-sm-12 p-0">




                                </div>
                            </div>

                        </section>
                        <div class="bottom-end">

                        </div>

                            <a href="#top" class="gotop">
                                <i class="fa fa-angle-up"></i>
                            </a>
                            <div id="loading">

                            </div>

                        <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
                        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
                        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
                        <script type="text/javascript" src="{% static 'assets/js/ResizeSensor.js'%}"></script>
                        <script type="text/javascript" src="{% static 'assets/js/sticky-sidebar.min.js'%}"></script>
                        <script src="{% static 'assets/js/flickity.js' %}"></script>
                        <script>
                            $(document).ready(function(){
                                videosectionCorrection();
                                $(window).resize(function(){
                                    videosectionCorrection();
                                })

                            })
                            function videosectionCorrection(){
                                var h1=  $(".flickity-viewport").first().css('padding-top');

                                  $(".carousel-nav").css({'max-height':h1});
                                  h1 ='calc('+h1+' + 10px)';
                                  $(".most-visited").css({'max-height':h1});

                                  var h2 = 'calc('+h1+' - 42.75px)';
                                  $(".most-content").css({'max-height':h2});
                            }
                                //video carousel flickity

                                var $carousel = $('.carousel').flickity();

                               var $carouselNav = $('.carousel-nav');
                               var $carouselNavCells = $carouselNav.find('.carousel-cell');

                               $carouselNav.on( 'click', '.carousel-cell', function( event ) {

                               var index = $( event.currentTarget ).index();
                               $carousel.flickity( 'select', index );
                               });

                               var flkty = $carousel.data('flickity');
                               var navTop  = $carouselNav.position().top;
                               var navCellHeight = $carouselNavCells.height();
                               var navHeight = $carouselNav.height();

                               $carousel.on( 'select.flickity', function() {
                               // set selected nav cell
                               $carouselNav.find('.is-nav-selected').removeClass('is-nav-selected');
                               var $selected = $carouselNavCells.eq( flkty.selectedIndex )
                                   .addClass('is-nav-selected');
                               // scroll nav
                               var scrollY = $selected.position().top +
                                   $carouselNav.scrollTop() - ( navHeight + navCellHeight ) / 2;
                               $carouselNav.animate({
                                   scrollTop: scrollY
                               });
                               });
                           </script>




                    </body>
                </html>

mysite/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}


        <section id="main-content">
            <div class="row main-content">

                <div class="col-xl-2 col-lg-3 col-md-12 p-0 order2">
                    <div class="sidebar2">
                    <div class="sidebar__inner2">
                        <div class="bg-white">
                            <nav id="side-nav" class="rtl">
                                <ul>

                                  <div class="">
                                    <form method="post" >
                                      {% csrf_token %}
                                        <table border="3">
                                      {{ form }}
                                      </table>
                                      <button type="submit">Submit</button>
                                    </form>
                                  </div>



                                </ul>

                            </nav>
                        </div>
                    </div>
                </div>
            </div>
                    <div class="col-xl-10 col-lg-9 col-md-12 p-0 orde1">
                        <div class="content">
                            <section id="books-section">

                             <div class="books-div">
                                 <div class="row">
                                   {% for item in clinic_list %}
                                     <div class="col-xl-3 col-lg-3 col-md-4 col-sm-12">
                                       <a href="{% url 'clinics:clinic_details' id=item.id %}">
                                         <div class="book-content">
                                             <img src="{% if item.image %}{{ item.image.url }} {% endif %}">
                                             <p>{{ item.name }}</p>
                                             <p>{{ item.field }}</p>
                                             <a class="tag" href="">{{ item.phone }}</a>
                                         </div>
                                         </a>
                                     </div>
                                    {% endfor %}


                                 </div>





                            </div>
                        </section>
                        </div>
                    </div>
            </div>
        </section>

        {% endblock %}

mysite/templates/search_results.html
{% extends "base.html" %}

{% load static %}

{% block content %}


        <section id="main-content">
            <div class="row main-content">

                <div class="col-xl-2 col-lg-3 col-md-12 p-0 order2">
                    <div class="sidebar2">
                    <div class="sidebar__inner2">
                        <div class="bg-white">
                            <nav id="side-nav" class="rtl">
                                <ul>

                                  <div class="">
                                    <form method="post" >
                                      {% csrf_token %}
                                        <table border="3">
                                      {{ form }}
                                      </table>
                                      <button type="submit">Submit</button>
                                    </form>
                                  </div>



                                </ul>

                            </nav>
                        </div>
                    </div>
                </div>
            </div>
                    <div class="col-xl-10 col-lg-9 col-md-12 p-0 orde1">
                        <div class="content">
                            <section id="books-section">

                             <div class="books-div">
                                 <div class="row">
                                   {% for item in search_list %}
                                     <div class="col-xl-3 col-lg-3 col-md-4 col-sm-12">
                                       <a href="{% url 'clinics:clinic_details' id=item.id %}">
                                         <div class="book-content">
                                             <img src="{% if item.image %}{{ item.image.url }} {% endif %}">
                                             <p>{{ item.name }}</p>
                                             <a class="tag" href="">{{ item.phone }}</a>
                                         </div>
                                         </a>
                                     </div>
                                    {% endfor %}


                                 </div>





                            </div>
                        </section>
                        </div>
                    </div>
            </div>
        </section>

        {% endblock %}