mysite/booking/urls.py
from django.urls import path,include
from booking.views import NewBooking

app_name ="booking"

urlpatterns = [

    path('newbooking/<int:id>/',NewBooking.as_view(), name='newbooking_'),




]

mysite/clinics/urls.py
from django.urls import path,include
from clinics.views import ClinicsView,NewClinic,ClinicDetails

app_name ="clinics"

urlpatterns = [

    path('clinics/',ClinicsView.as_view(), name='clinics'),
    path('newclinics/',NewClinic.as_view(), name='newclinics'),
    path('details/<int:id>/',ClinicDetails.as_view(), name='clinic_details'),



]

mysite/home/urls.py
from django.urls import path,include
from home.views import IndexView

app_name ="home"

urlpatterns = [

    path('',IndexView.as_view(), name='index'),
    path('accounts/', include('django.contrib.auth.urls')),



]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', 'accounts')),
    path('clinics/', include('clinics.urls', 'clinics')),
    path('booking/', include('booking.urls', 'booking')),
    path('', include('home.urls', 'home')),
    path('auth/', include('rest_framework.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/clinics/models.py
from django.db import models
from django.contrib.auth.models import User


class Clinics(models.Model):
    user = models.ForeignKey(User,related_name="clinic_nam", on_delete=models.CASCADE)
    name = models.CharField(max_length=30,  null=True, blank=True  )
    address = models.CharField(max_length=30,  null=True, blank=True  )
    phone = models.CharField(max_length=30,  null=True, blank=True  )
    max_patient = models.IntegerField( null=True, blank=True  )
    field = models.CharField(max_length=30,  null=True, blank=True  )
    image = models.ImageField(upload_to = 'clinics_images/',null=True, blank=True)
    def __str__(self):
        return self.name

mysite/clinics/forms.py
from django import forms

class InsertClinic(forms.Form):
    name = forms.CharField(max_length=30)
    address = forms.CharField(max_length=30)
    phone = forms.CharField(max_length=30 )
    image = forms.ImageField()

mysite/clinics/views.py
from django.shortcuts import render,get_object_or_404
from clinics.models import Clinics
from django.views.generic import TemplateView
from clinics.forms import InsertClinic
from booking.models import Queues
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.




class ClinicDetails(LoginRequiredMixin,TemplateView):

    template_name='clinics/clinic_details.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        single_clinics = self.get_object()
        # patent_in_queue =Queues.objects.filter(user = self.request.user).count()
        patent_in_queue =Queues.objects.select_related('clinic').filter(user =self.request.user ).filter(clinic=single_clinics ).count()
        last_in_queue =Queues.objects.filter(user = self.request.user).last()
        context['patent_in_queue'] = patent_in_queue
        context['last_in_queue'] = last_in_queue
        context['single_clinics'] = single_clinics

        return context

    def get_object(self):
         return get_object_or_404(Clinics, pk=self.kwargs.get("id"))


class ClinicsView(TemplateView):
    template_name = "index.html"


    def get_context_data(self):
        print('ClinicsView')
        context = super(ClinicsView, self).get_context_data()
        clinic_list =Clinics.objects.all()
        context['clinic_list'] = clinic_list
        return context



class NewClinic(TemplateView):
    template_name = "clinics/new_clinics.html"

    def get_context_data(self):

        context = super(NewClinic, self).get_context_data()
        form = InsertClinic()
        context['form'] = form
        return context

    def post(self, request, *args, **kwargs):
        print('Post')
        form = InsertClinic(self.request.POST,self.request.FILES)
        clinic_list =Clinics.objects.all()
        clinic_obj = Clinics()
        print( request.user)
        clinic_obj.user = request.user
        clinic_obj.name = request.POST.get("name")
        clinic_obj.address = request.POST.get("address")
        clinic_obj.phone = request.POST.get("phone")
        clinic_obj.image = request.FILES['image']
        clinic_obj.save()
        return render(request,'index.html',{'clinic_list':clinic_list})

mysite/templates/clinics/clinic_details.html
{% extends "base.html" %}

{% load static %}

{% block content %}


        <section id="main-content">
            <div class="row main-content">

                <div class="col-xl-2 col-lg-3 col-md-12 p-0 order2">
                    <div class="sidebar2">
                    <div class="sidebar__inner2">
                        <div class="bg-white">
                            <nav id="side-nav" class="rtl">
                                <ul>





                                </ul>

                            </nav>
                        </div>
                    </div>
                </div>
            </div>
                    <div class="col-xl-10 col-lg-9 col-md-12 p-0 orde1">
                        <div class="content">
                            <section id="books-section">

                             <div class="books-div">
                                 <div class="row">

                                     <div class="col-xl-3 col-lg-3 col-md-4 col-sm-12">
                                       <a href="">
                                         <div class="book-content">
                                             <img src="{% if single_clinics.image %}{{ single_clinics.image.url }} {% endif %}">
                                             <p>{{ single_clinics.name }}</p>
                                             <a class="tag" href="">{{ single_clinics.phone }}</a><br>
                                             <a class="tag" href="">Booked : {{ patent_in_queue }}</a>/
                                             <a class="tag" href="">Available : {{ single_clinics.max_patient }} </a>
                                             <a class="tag" href="">Last Turn : {{ last_in_queue.date }} </a>
                                             <br>
                                             <a class="tag" href=" {% if single_clinics.image %} {% url 'booking:newbooking_'  id=single_clinics.id  %} {% endif %} ">Book</a>
                                         </div>
                                         </a>
                                     </div>


                                 </div>





                            </div>
                        </section>
                        </div>
                    </div>
            </div>
        </section>

        {% endblock %}

mysite/templates/clinics/list.html
{% extends "base.html" %}

{% load static %}

{% block content %}


        <section id="main-content">
            <div class="row main-content">

                <div class="col-xl-2 col-lg-3 col-md-12 p-0 order2">
                    <div class="sidebar2">
                    <div class="sidebar__inner2">
                        <div class="bg-white">
                            <nav id="side-nav" class="rtl">
                                <ul>





                                </ul>

                            </nav>
                        </div>
                    </div>
                </div>
            </div>
                    <div class="col-xl-10 col-lg-9 col-md-12 p-0 orde1">
                        <div class="content">
                            <section id="books-section">

                             <div class="books-div">
                                 <div class="row">



                                 </div>





                            </div>
                        </section>
                        </div>
                    </div>
            </div>
        </section>

        {% endblock %}

mysite/templates/clinics/new_clinics.html
{% extends "base.html" %}

{% load static %}

{% block content %}


        <section id="main-content">
            <div class="row main-content">

                <div class="col-xl-2 col-lg-3 col-md-12 p-0 order2">
                    <div class="sidebar2">
                    <div class="sidebar__inner2">
                        <div class="bg-white">
                            <nav id="side-nav" class="rtl">
                                <ul>





                                </ul>

                            </nav>
                        </div>
                    </div>
                </div>
            </div>
                    <div class="col-xl-3 col-lg-3 col-md-3 p-0 orde1">
                        <div class="content">
                            <section id="books-section">

                             <div class="books-div">
                               <form method="post" novalidate enctype="multipart/form-data">
                                 {% csrf_token %}
                                   <table border="1">
                                 {{ form }}
                                 </table>
                                 <button type="submit">Submit</button>
                               </form>

                                 </div>





                            </div>
                        </section>
                        </div>
                    </div>
            </div>
        </section>

        {% endblock %}